Revert "SKETCH-1034. Update export dialog to be compatible with WASM save file API"
This reverts commit 9962015ab85807e0a991d21c5e67c47a1782b6a5.
Windows make all fails:
..\..\..\..\..\src\mmshare\src\schrodinger\sketcher\cut_copy_action_manager.cpp(42): error C3493: 'default_format' cannot be implicitly captured because no default capture mode has been specified