Revert "SHARED-9335: Remove the "advanced query status" property from sketcher"
This reverts commit 00512273046a2ddbe361067344155484b1d5974e.

In file included from /software/lib/Linux-x86_64/gcc-9.3.0/include/c++/9.3.0/algorithm:62,
                 from ../../../../../src/mmshare/test/schrodinger/sketcher/test_ChemicalKnowledge.cpp:3:
/software/lib/Linux-x86_64/gcc-9.3.0/include/c++/9.3.0/bits/stl_algo.h: In instantiation of ‘_Iterator std::__find_if(_Iterator, _Iterator, _Predicate) [with _Iterator = RDKit::AtomIterator_<const RDKit::Atom, const RDKit::ROMol>; _Predicate = __gnu_cxx::__ops::_Iter_pred<std::_Mem_fn<bool (RDKit::Atom::*)() const> >]’:
/software/lib/Linux-x86_64/gcc-9.3.0/include/c++/9.3.0/bits/stl_algo.h:3963:28:   required from ‘_IIter std::find_if(_IIter, _IIter, _Predicate) [with _IIter = RDKit::AtomIterator_<const RDKit::Atom, const RDKit::ROMol>; _Predicate = std::_Mem_fn<bool (RDKit::Atom::*)() const>]’
/software/lib/Linux-x86_64/gcc-9.3.0/include/c++/9.3.0/bits/stl_algo.h:526:47:   required from ‘bool std::none_of(_IIter, _IIter, _Predicate) [with _IIter = RDKit::AtomIterator_<const RDKit::Atom, const RDKit::ROMol>; _Predicate = std::_Mem_fn<bool (RDKit::Atom::*)() const>]’
/software/lib/Linux-x86_64/gcc-9.3.0/include/c++/9.3.0/bits/stl_algo.h:544:27:   required from ‘bool std::any_of(_IIter, _IIter, _Predicate) [with _IIter = RDKit::AtomIterator_<const RDKit::Atom, const RDKit::ROMol>; _Predicate = std::_Mem_fn<bool (RDKit::Atom::*)() const>]’
../../../../../src/mmshare/test/schrodinger/sketcher/test_ChemicalKnowledge.cpp:77:59:   required from here
/software/lib/Linux-x86_64/gcc-9.3.0/include/c++/9.3.0/bits/stl_algo.h:162:34: error: no matching function for call to ‘__iterator_category(RDKit::AtomIterator_<const RDKit::Atom, const RDKit::ROMol>&)’
  162 |          std::__iterator_category(__first));
      |          ~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~
In file included from /software/lib/Linux-x86_64/gcc-9.3.0/include/c++/9.3.0/bits/stl_algobase.h:65,
                 from /software/lib/Linux-x86_64/gcc-9.3.0/include/c++/9.3.0/algorithm:61,
                 from ../../../../../src/mmshare/test/schrodinger/sketcher/test_ChemicalKnowledge.cpp:3:
/software/lib/Linux-x86_64/gcc-9.3.0/include/c++/9.3.0/bits/stl_iterator_base_types.h:205:5: note: candidate: ‘template<class _Iter> constexpr typename std::iterator_traits<_Iterator>::iterator_category std::__iterator_category(const _Iter&)’
  205 |     __iterator_category(const _Iter&)
      |     ^~~~~~~~~~~~~~~~~~~
/software/lib/Linux-x86_64/gcc-9.3.0/include/c++/9.3.0/bits/stl_iterator_base_types.h:205:5: note:   template argument deduction/substitution failed:
/software/lib/Linux-x86_64/gcc-9.3.0/include/c++/9.3.0/bits/stl_iterator_base_types.h: In substitution of ‘template<class _Iter> constexpr typename std::iterator_traits<_Iterator>::iterator_category std::__iterator_category(const _Iter&) [with _Iter = RDKit::AtomIterator_<const RDKit::Atom, const RDKit::ROMol>]’:
/software/lib/Linux-x86_64/gcc-9.3.0/include/c++/9.3.0/bits/stl_algo.h:162:34:   required from ‘_Iterator std::__find_if(_Iterator, _Iterator, _Predicate) [with _Iterator = RDKit::AtomIterator_<const RDKit::Atom, const RDKit::ROMol>; _Predicate = __gnu_cxx::__ops::_Iter_pred<std::_Mem_fn<bool (RDKit::Atom::*)() const> >]’
/software/lib/Linux-x86_64/gcc-9.3.0/include/c++/9.3.0/bits/stl_algo.h:3963:28:   required from ‘_IIter std::find_if(_IIter, _IIter, _Predicate) [with _IIter = RDKit::AtomIterator_<const RDKit::Atom, const RDKit::ROMol>; _Predicate = std::_Mem_fn<bool (RDKit::Atom::*)() const>]’